"""create evaluations

Revision ID: 7f5de6b54648
Revises: 7f613b8c716c
Create Date: 2026-09-29 18:41:18.402339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5de6b54648'
down_revision: Union[str, Sequence[str], None] = '7f613b8c716c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'ARCHIVED', name='evaluation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_academic_year'), 'evaluations', ['academic_year'], unique=False)
    op.create_index(op.f('ix_evaluations_class_id'), 'evaluations', ['class_id'], unique=False)
    op.create_index(op.f('ix_evaluations_name'), 'evaluations', ['name'], unique=False)
    op.create_index(op.f('ix_evaluations_semester'), 'evaluations', ['semester'], unique=False)
    op.create_index(op.f('ix_evaluations_status'), 'evaluations', ['status'], unique=False)
    op.create_index(op.f('ix_evaluations_subject_id'), 'evaluations', ['subject_id'], unique=False)
    op.create_index(op.f('ix_evaluations_teacher_id'), 'evaluations', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_teacher_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_subject_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_status'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_semester'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_name'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_class_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_academic_year'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
