"""create learning outcomes table

Revision ID: 7f613b8c716c
Revises: 7d111e90c24e
Create Date: 2026-09-29 14:14:12.133347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f613b8c716c'
down_revision: Union[str, Sequence[str], None] = '7d111e90c24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_outcomes_code'), 'learning_outcomes', ['code'], unique=False)
    op.create_index(op.f('ix_learning_outcomes_subject_id'), 'learning_outcomes', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_outcomes_subject_id'), table_name='learning_outcomes')
    op.drop_index(op.f('ix_learning_outcomes_code'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    # ### end Alembic commands ###
